apiVersion: apps/v1
kind: Deployment
metadata:
 name: demo
 namespace: optimization-demo
spec:
 selector:
   matchLabels:
     app: demo
 replicas: 1
 template:
   metadata:
     labels:
       app: demo
   spec:
     containers:
     - name: demo
       image: k8s.gcr.io/hpa-example
       ports:
       - containerPort: 80
       resources:
         limits:
           cpu: 1000m
           memory: 500Mi
         requests:
           cpu: 1000m
           memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
 name: demo
 namespace: optimization-demo
 labels:
   app: demo
spec:
 ports:
 - port: 80
 selector:
   app: demo
