apiVersion: apps/v1
kind: Deployment
metadata:
 name: demo
 namespace: optimization-demo
spec:
 selector:
   matchLabels:
     app: demo
 replicas: 1
 template:
   metadata:
     labels:
       app: demo
   spec:
     containers:
     - name: demo
       image: k8s.gcr.io/hpa-example
       ports:
       - containerPort: 80
       resources:
         limits:
           cpu: 2000m
           memory: 1000Mi
         requests:
           cpu: 1000m
           memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
 name: demo
 namespace: optimization-demo
 labels:
   app: demo
spec:
 ports:
 - port: 80
 selector:
   app: demo
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: demo-deployment
 namespace: optimization-demo
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: demo
 minReplicas: 2
 maxReplicas: 5
 targetCPUUtilizationPercentage: 80
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: demo
 minReplicas: 1
 maxReplicas: 3
 targetCPUUtilizationPercentage: 50
